[2022-05-29 16:06:34,191] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 16:06:34,196] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user scheduled__2022-05-28T00:00:00+00:00 [queued]>
[2022-05-29 16:06:34,196] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 16:06:34,196] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-29 16:06:34,196] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 16:06:34,228] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_user> on 2022-05-28 00:00:00+00:00
[2022-05-29 16:06:34,230] {standard_task_runner.py:52} INFO - Started process 106962 to run task
[2022-05-29 16:06:34,235] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'processing_user', 'scheduled__2022-05-28T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp1v9li3xl', '--error-file', '/tmp/tmpp74ybdpp']
[2022-05-29 16:06:34,235] {standard_task_runner.py:80} INFO - Job 5: Subtask processing_user
[2022-05-29 16:06:34,309] {task_command.py:370} INFO - Running <TaskInstance: user_processing.processing_user scheduled__2022-05-28T00:00:00+00:00 [running]> on host airflowvm
[2022-05-29 16:06:34,487] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T00:00:00+00:00
[2022-05-29 16:06:34,518] {python.py:173} INFO - Done. Returned value was: None
[2022-05-29 16:06:34,525] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20220528T000000, start_date=20220529T160634, end_date=20220529T160634
[2022-05-29 16:06:34,570] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-29 16:06:34,630] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
